### ISSUE TITLE
Address review comments before deployment

### ISSUE THREAD

**Issue by aaaaalbert** [SeattleTestbed/continuous-integration#2]
We have a few unaddressed comments for the CI config files in https://github.com/SeattleTestbed/repy_v2/pull/112 . Let's address them so we launch CI!

**Comment by lukpueh** [comment]
@kellender and @Awwad already PR'ed CI configuration files into several SeattleTestbed components. As @aaaaalbert suggests, let's close those PRs, address unaddressed comments here and open new PRs based on the fresh config files.

**Comment by lukpueh** [comment]
@awwad: Do we need  [e1f8673b](https://github.com/SeattleTestbed/seash/pull/98/commits/e1f8673b47f3c145b1e806483026bb7e59bcdcd5)?

**Comment by aaaaalbert** [comment]
This was added test due to SeattleTestbed/seash#99, `readline`-induced seash unit test errors. We don't have a complete fix for that issue yet.

And yes, @awwad's addition of `TERM=...` appears to suppress the problem, see [the relevant discussion on the issue](https://github.com/SeattleTestbed/seash/issues/99#issuecomment-179407931).
