### ISSUE TITLE
`ImportError: No module named argparse` in Python2.5 (Travis-CI) 

### ISSUE THREAD

**Issue by lukpueh** [SeattleTestbed/continuous-integration#5]
In Travis-CI we run the unit test framework on (amongst other versions) Python 2.5, which we have to [install manually via the deadsnakes repo](https://github.com/SeattleTestbed/continuous-integration/blob/master/.travis.yml#L35-L44) _(Note: we ignore Python 2.5 in Appveyor)_. 

But Python 2.5 doesn't have the `argparse` module in its standard library, which `utf.py` requires since [recently](https://github.com/SeattleTestbed/utf/commit/3634f6189fb9e9549b6e0353b1de2fdc86828697).

In consequence the unit tests fail before they even start (here is a sample [Travis job log](https://travis-ci.org/SeattleTestbed/repy_v2/jobs/154146489#L350-L354)) with the following exception:

``` python
Traceback (most recent call last):
  File "utf.py", line 54, in <module>
    import argparse
ImportError: No module named argparse
```

The solution is to install [argparse via pypi](https://pypi.python.org/pypi/argparse) prior to running `utf.py`. 

**Caution:** when using `setup.py`, `easy_install` or `pip` make sure to use the Python 2.5 versions and to also execute them with Python2.5. (c.f. [Kura's gist](https://gist.github.com/kura/8517802))

**Comment by lukpueh** [comment]
Should we also create an issue in the [utf repo issue tracker](https://github.com/SeattleTestbed/utf/issues)? IMHO, we won't fix this in `utf.py` anyway.

The only thing we could do there is to catch the exception and replace the traceback with something like, `Please install argparse!` which is about as descriptive as `ImportError: No module named argparse`.

**Comment by aaaaalbert** [comment]
FYI, I have a branch of my fork of SeattleTestbed/utf on Travis to show that this functionality works with actual code: https://travis-ci.org/aaaaalbert/utf/jobs/155035256
